"""Skill-based AI workflow helpers.

This project is a Codex Skill. Python must not call external LLM APIs. Instead,
Codex uses the prompt and schema files to generate JSON, and Python validates
that JSON before publishing it to Notion.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Protocol

from src.analyzer.prompt_loader import AnalyzerPrompts


class SkillAIWorkflowError(RuntimeError):
    """Raised when a skill-based AI analysis artifact is invalid."""


class AIClient(Protocol):
    """Test/dummy protocol for modules that accept pre-supplied AI outputs."""

    def analyze_json(self, prompt: str, payload: Mapping[str, Any]) -> Mapping[str, Any]:
        """Return already structured JSON from a caller-provided implementation."""


@dataclass(frozen=True)
class SkillAnalysisRequest:
    """Instruction package for Codex to perform AI learning analysis."""

    title: str
    transcript: str
    prompts: AnalyzerPrompts
    schema: Mapping[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "transcript": self.transcript,
            "prompts": {
                "summary": self.prompts.summary,
                "metadata": self.prompts.metadata,
                "expression": self.prompts.expression,
            },
            "schema": dict(self.schema),
        }


def load_analysis_schema(path: Path = Path("skill/schemas/ai_analysis_schema.json")) -> Mapping[str, Any]:
    """Load the JSON schema used by Codex-generated AI analysis output."""
    if not path.exists():
        raise SkillAIWorkflowError(f"AI analysis schema does not exist: {path}")

    try:
        schema = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SkillAIWorkflowError(f"AI analysis schema is invalid JSON: {exc.msg}") from exc

    if not isinstance(schema, Mapping):
        raise SkillAIWorkflowError("AI analysis schema must be a JSON object.")
    return schema


def parse_generated_analysis_json(content: str) -> Mapping[str, Any]:
    """Parse JSON generated by Codex for downstream validation."""
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError as exc:
        raise SkillAIWorkflowError(f"AI analysis output is invalid JSON: {exc.msg}") from exc

    if not isinstance(parsed, Mapping):
        raise SkillAIWorkflowError("AI analysis output must be a JSON object.")
    return parsed


def read_generated_analysis_file(path: Path) -> Mapping[str, Any]:
    """Read a Codex-generated AI analysis JSON file."""
    if not path.exists():
        raise SkillAIWorkflowError(f"AI analysis output file does not exist: {path}")
    return parse_generated_analysis_json(path.read_text(encoding="utf-8"))
